[package]
name = "chain"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
subxt = "0.35"
tokio = { version =  "1", features = ["rt-multi-thread", "macros"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
