[advisories]
unmaintained = "allow"

[licenses]
unlicensed = "allow"
allow = ["Apache-2.0", "BSD-2-Clause", "BSD-3-Clause", "CC0-1.0", "MIT", "ISC", "Unicode-DFS-2016"]

[licenses.private]
ignore = true
