[package]
name = "bioauth_logic"
version = "0.1.0"
edition = "2021"

[dependencies]
bioauth_settings = { version = "0.1", path = "../bioauth_settings" }

tracing = "0.1"

[dev-dependencies]
tracing-test = "0.2"
