[package]
name = "database"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
envfury = "0.2"
tracing = "0.1"
diesel = { version = "2.1", features = ["postgres"] }
diesel-async = { version = "0.4", features = ["postgres", "bb8"] }
tokio = { version = "1", features = ["full"] }
