[package]
name = "telegram"
version = "0.1.0"
edition = "2021"

[dependencies]
chain = { version = "0.1", path = "../chain" }

anyhow = "1.0.71"
derivative = "2"
indoc = "2"
serde = "1"
subxt = "0.35"
teloxide = { version = "0.12", features = ["macros"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
